WORDS = [
    "TIGER", "SHARK", "LION", "CHAIR", "BEACH", "HOUSE",
    "BIRD", "WEATHER", "WINDOW", "APPLE", "ORANGE", "HORSE",
    "CARDS", "CASTLE", "TRUCK", "MONDAY", "TUESDAY", "WEDNESDAY",
    "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY", "PENCIL", "GOAT",
    "PHONE", "SHOE", "FLOWER", "GREEN", "BLUE", "YELLOW", "WHALE"

]
